#!/opt/bin/bash

# speedtest.net > html bash script 
# formats json output from speedtest-cli into a html file containing a <table/>
# drop this file into /etc/cron.hourly to perform automated hourly tests

# dependencies: 
# ookla speedtest cli for performing speed tests via speedtest.net (https://www.speedtest.net/apps/cli)
# jq for command line json parsing (https://stedolan.github.io/jq/)

SPEED_TEST_CMD="/root/speedtest -f json-pretty" 
OUT_FILE=/volume1/Web/speedtest.htm
LOG_FILE=/root/log-speedtest.log

exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>$LOG_FILE 2>&1

#perform the speed test
SPEED_TEST=`$SPEED_TEST_CMD`

#json parse the response via jq
HOST=$(echo "$SPEED_TEST" | /opt/bin/jq -r '.server.host')
PING=$(echo "$SPEED_TEST" | /opt/bin/jq '.ping.latency')
DOWN_BW=$(echo "$SPEED_TEST" | /opt/bin/jq '.download.bandwidth')
UP_BW=$(echo "$SPEED_TEST" | /opt/bin/jq '.upload.bandwidth')
URL=$(echo "$SPEED_TEST" | /opt/bin/jq -r '.result.url')

# Convert bandwidth (bytes/s) -> Mbps
DOWN=$(echo "$DOWN_BW" | /opt/bin/jq '. * 8 / 1000000')
UP=$(echo "$UP_BW"   | /opt/bin/jq '. * 8 / 1000000')

#apply rounding
PING=`printf '%.*f\n' 2 $PING`
DOWN=`printf '%.*f\n' 2 $DOWN`
UP=`printf '%.*f\n' 2 $UP`

#strip quotes from strings
#HOST=`echo $HOST | tr -d '"'`
#URL=`echo $URL | tr -d '"'`

#replace line #1 in the file with the new <tr/> content
NEW_ROW="<tr onclick=\"window.open('$URL','_blank')\" style=\"cursor:pointer\"><td>$(date '+%d/%m/%Y %T')</td><td>$HOST</td><td>$PING ms</td><td>$DOWN Mbps</td><td>$UP Mbps</td></tr>"
sed -i "1c${NEW_ROW}" $OUT_FILE

#insert a new line #1
echo -e "<html><head><title>Speedtest Log</title><style>html{background:#121212;color:#FFFFFF;}table{width:100%;border-collapse:collapse;font-family:Verdana,Geneva,Tahoma,sans-serif;}table thead{font-weight:bold;}table td{padding:10px;border:#4E95F4 1px solid}</style></head><body><table><thead><tr><td>Timestamp</td><td>Host</td><td>Ping</td><td>Down</td><td>Up</td></tr></thead><tbody>\n$(cat $OUT_FILE)" > $OUT_FILE

echo $NEW_ROW

#output formatted json to stdout
echo $SPEED_TEST | /opt/bin/jq .
